### ISSUE TITLE
Apache Arrow Interoperability

### ISSUE THREAD

**Issue by nicosuave** [ankane/polars-ruby#10]
Similar to how Polars and other libraries backed by Apache Arrow in Python (say, DuckDB) have interoperability, it would be great to have the same in Ruby.

Might be worth considering implementing `to_arrow` (which I saw you [commented out](https://github.com/ankane/polars-ruby/blob/d52de3edf70762d9c31da10bb3f2f59c06136c71/lib/polars/data_frame.rb#L672)) using the [official Ruby Arrow bindings](https://github.com/apache/arrow/blob/main/ruby/README.md). To be fair, I've not looked into this much more deeply (I would be happy to if you would like a contribution); just being an optimist!

**Comment by ankane** [comment]
Hey @nicosuave, thanks for the suggestion. I'm not planning to add integration with the Ruby Arrow bindings right now, but may revisit in the future. If you decide to fork and add, feel free to share.

Link for future reference: [DuckDB with Polars](https://duckdb.org/docs/guides/python/polars.html)
