### ISSUE TITLE
Add #sink_parquet method

### ISSUE THREAD

**Issue by shreeve** [ankane/polars-ruby#12]
For files bigger than memory, it would be great to be able to use:

```ruby
Polars.scan_csv(csv_file).sink_parquet(parquet_file)
```

**Comment by ankane** [comment]
Thanks @shreeve, added in the commit above.

**Comment by shreeve** [comment]
@ankane - You are the man! Thank you so much.

**Comment by shreeve** [comment]
@ankane - This is extremely helpful. I was unable to process several large files and now I am able to do so. Thanks again.

**Comment by ankane** [comment]
Great to hear. Just pushed a new release (0.4.0).
