### ISSUE TITLE
Not sure if casting works

### ISSUE THREAD

**Issue by zewelor** [ankane/polars-ruby#14]
Hi

Thanks for this wonderful gem ! I'm playing with it since few days. I've tried to use cast ( to speed up / optimize data ). But not sure if it works. With following code I get still UTF8 fields.

```
df['symbol'].cast(Polars::Categorical)
df['date'].str.strptime(:date, '%Y-%m-%d').cast(Polars::Date)
p df.schema
```

```
{"symbol"=>Polars::Utf8, "date"=>Polars::Utf8, "price"=>Polars::Float64}
```

**Comment by ankane** [comment]
Hi @zewelor, `cast` doesn't modify in-place. You can use:

```ruby
df = df.with_columns([
  Polars.col("symbol").cast(Polars::Categorical),
  Polars.col("date").str.strptime(:date, "%Y-%m-%d")
])
```

After the next release, it'll also be possible to use:

```ruby
df["symbol"] = df["symbol"].cast(Polars::Categorical)
df["date"] = df["date"].str.strptime(:date, "%Y-%m-%d")
```

**Comment by zewelor** [comment]
Oh I've read readme wrong then. Thank you very much !
