### ISSUE TITLE
First-time contribution

### ISSUE THREAD

**Issue by arbox** [ankane/polars-ruby#19]
Hey @ankane,

I'd like to dive into Polars code and make something useful with it.

Do you have an idea for the first-time contribution? Something the project needs and you have no time for.

Is the feature parity to Python API already achieved?

Thank you :)

**Comment by ankane** [comment]
Hi @arbox, adding support for the `schema_overrides` option to [DataFrame.new](https://github.com/ankane/polars-ruby/blob/5ec1221657c2e0e7ce94faeaa34cfe45086f6fd8/lib/polars/data_frame.rb#L21C5-L23) could be a good candidate. There are also a number of other places with `todo` (case-insensitive) in the code. It's essentially porting code from [py-polars](https://github.com/pola-rs/polars/tree/rs-0.30.0/py-polars).
