### ISSUE TITLE
`groupby_dynamic` is throwing a `TypeError` since 0.5.0

### ISSUE THREAD

**Issue by davidderus** [ankane/polars-ruby#20]
Hi,

After updating to polars-df `0.5.0`, I noticed that some code relying on `groupby_dynamic` is not working anymore. It throws the following error:
```
polars-df-0.5.0-arm64-darwin/lib/polars/lazy_frame.rb:1236:in `groupby_dynamic':
no implicit conversion of String into Polars::RbExpr (TypeError)
```

I'm on macOS Ventura (`arm64`) with ruby `3.2.0`.

Please note that `groupby_rolling` does not seem to be affected.

## Step to reproduce

The issue can be reproduced with the example code from [the method documentation](https://www.rubydoc.info/gems/polars-df/Polars/DataFrame#groupby_dynamic-instance_method):

```ruby
# frozen_string_literal: true

require 'polars-df'

df = Polars::DataFrame.new(
  {
    'time' => Polars.date_range(
      DateTime.new(2021, 12, 16),
      DateTime.new(2021, 12, 16, 3),
      '30m',
    ),
    'n' => 0..6,
  },
)

df.groupby_dynamic('time', every: '1h', closed: 'right').agg(
  [
    Polars.col('time').min.alias('time_min'),
    Polars.col('time').max.alias('time_max'),
  ],
)
```

And the output with v0.5.0 is:

```shell
/Users/david/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.5.0-arm64-darwin/lib/polars/lazy_frame.rb:1236:in `groupby_dynamic': no implicit conversion of String into Polars::RbExpr (TypeError)
        from /Users/david/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.5.0-arm64-darwin/lib/polars/lazy_frame.rb:1236:in `groupby_dynamic'
        from /Users/david/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.5.0-arm64-darwin/lib/polars/dynamic_group_by.rb:37:in `agg'
        from app.rb:16:in `<main>'
```

**Comment by ankane** [comment]
Hi @davidderus, thanks for reporting! Fixed the error in the commit above (as well as the test for the examples).

**Comment by davidderus** [comment]
Hi @ankane, I've pulled the latest commit from `master` and this issue is indeed fixed.

Thank you very much for this awesome Polars wrapper.
I'm glad I can still do some data analysis in Ruby thanks to this gem.
