### ISSUE TITLE
Noob question about plotting

### ISSUE THREAD

**Issue by iovis** [ankane/polars-ruby#24]
Hi!

I sometimes use `pandas` + `matplotlib` in Python to do quick and dirty data visualizations and I wanted to give polars a try!

With `matplotlib` I can do `plt.plot(...); plt.show()` and it shows a little window with the plot. I was trying to do the same with `polars` and `vega` and got this far:

```rb
require "polars-df"
require "vega"

df = Polars.read_csv("data.csv")

File.write("index.html", df.plot("a", "b"))  # I saw `.plot` spit out an HTML fragment
system("open index.html")
```

I'm guessing what I'm missing is embedding the HTML fragment in a webpage that bundles the `vega` libraries? I saw there were some CDN links in the Vega repo, so I'm guessing I could leverage those?

Would it make sense to have an API that would spit out a full doc, maybe including the CDN includes, for people like me that would like to do some quick data visualization? I'm a complete noob at this, so I can believe I'm weird and there's better ways to do this haha.

**Comment by topofocus** [comment]
I am using bridgetown for this purpose

just install the vega-packages via yarn,
include the require-statements in config/initializers and you are done.

Configuration is done in the frontmatter part and visualization happens by including the erb in the website

``` 
~~ruby
{ 
  layout:  :home,
  title:  'Übersicht',
  strategie: Arcade::Strategie.find(symbol: 'Still')
}
~~~



## header
<figure>
<%= data.strategie.plot_result  %>
<figcaption>
  some caption  
</figcaption>
</figure>
```

in `plot_result` just put the vega-code

```ruby
module Arcade
class Strategie
def plot_result what: :all
 hole_value = Polars::DataFrame.new( ...)
 hole_result = hole_value.join( hole_theta, on: 'datum', how: 'outer' )
  ::Vega.lite
        .title( "" )
        .data( hole_result )
        .layer( [
 (...)
``` 
It simply works

**Comment by ankane** [comment]
@iovis It's an interesting idea and should work if you include the Vega libraries, but I'd try using Jupyter Notebook + IRuby for this.

@topofocus Thanks for sharing your approach as well.
