### ISSUE TITLE
~ Operand doesn't seem to work

### ISSUE THREAD

**Issue by paulreece** [ankane/polars-ruby#32]
Hey Andrew,  I just wanted to say that I'm super impressed by everything you've done for the Ruby Data community.  We're so lucky to have this library available to us!

I was just wondering if it is possible to add support for the `~` operand so we can filter for not of the selection.

Right now it returns a `NoMethodError`
```Ruby
irb(main):004:0> test = Polars::DataFrame.new({"name":["John", "Jeff", nil]})
=>
shape: (3, 1)
...
irb(main):005:0> test.filter(~Polars.col("name").is_null())
(irb):5:in `<main>': undefined method `~' for col("name").is_null():Polars::Expr (NoMethodError)

test.filter(~Polars.col("name").is_null())
```

In my code I just explicitly check `Polars.col("name") != nil` which is totally fine.  This is more of a cosmetic thing when using methods on selected columns

**Comment by ankane** [comment]
Hi @paulreece, thanks for the suggestion. Added support for `!` (as the Ruby equivalent) in the commit above, but you can also use:

```ruby
test.filter(Polars.col("name").is_not_null)
```

**Comment by paulreece** [comment]
Awesome!  I'm about to use `!` as I type this!!
