### ISSUE TITLE
Feature: Polars.cut

### ISSUE THREAD

**Issue by scart88** [ankane/polars-ruby#38]
Hey @ankane,

Thanks again for such a great gem!

What would be the best way to add Polars.cut method to this gem?
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.cut.html

I'm interested to create a histogram. 

I have a list from 0 to 30000 and the .cut method seems to be the best easiest way to create some ranges

Thank you!

**Comment by ankane** [comment]
Added in the commit above.

**Comment by scart88** [comment]
Thank you very much for the quick addition. 
I hope I can help in the future when I will learn more how to use it.
