### ISSUE TITLE
Top K: unknown keyword: :reverse (ArgumentError)

### ISSUE THREAD

**Issue by scart88** [ankane/polars-ruby#39]
irb(main):024:0> data.top_k(k: 5, reverse: true)

`installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/polars-df-0.7.0-arm64-darwin/lib/polars/expr.rb:1351:in `top_k': unknown keyword: :reverse (ArgumentError)`

**Comment by ankane** [comment]
Hi @scart88, thanks for reporting! Removed the `reverse` option and added a `bottom_k` method in the commit above to match the Python library.

**Comment by scart88** [comment]
Thank you so much!
