### ISSUE TITLE
Missing polars.Expr.replace

### ISSUE THREAD

**Issue by denjamio** [ankane/polars-ruby#47]
Would it be possible to include this functionality in the gem? https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.replace.html#polars.Expr.replace

I am looking for a way to be able to replace specific values without doing a full column replace using series

**Comment by ankane** [comment]
Hi @denjamio, thanks for the suggestion. Added in the commit above.

**Comment by denjamio** [comment]
How fast! Thanks
