### ISSUE TITLE
Error installing from github

### ISSUE THREAD

**Issue by denjamio** [ankane/polars-ruby#48]
After updating my gemfile to point to the github repository to take advantage of the latest changes, I get this error: 

Fetching https://github.com/ankane/polars-ruby
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/denjamio/.rvm/gems/ruby-3.2.3/bundler/gems/polars-ruby-30b14de12d61/ext/polars
/home/denjamio/.rvm/rubies/ruby-3.2.3/bin/ruby extconf.rb                                                  
checking for gcc... yes                                                                                    
checking for g++... yes                                                                                    
checking for gcc-ar... yes                                                                                 
                                                                                                           
current directory: /home/denjamio/.rvm/gems/ruby-3.2.3/bundler/gems/polars-ruby-30b14de12d61/ext/polars    
make DESTDIR\= sitearchdir\=./.gem.20240218-9771-14m2uo sitelibdir\=./.gem.20240218-9771-14m2uo clean      
                                                                                                           
current directory: /home/denjamio/.rvm/gems/ruby-3.2.3/bundler/gems/polars-ruby-30b14de12d61/ext/polars    
make DESTDIR\= sitearchdir\=./.gem.20240218-9771-14m2uo sitelibdir\=./.gem.20240218-9771-14m2uo            
generating target/release/libpolars.so (release)
cargo rustc  --manifest-path ./Cargo.toml --target-dir target --lib --profile release -- -C linker=gcc -L native=/home/denjamio/.rvm/rubies/ruby-3.2.3/lib -C link-arg=-lm -l       
pthread
   Compiling libc v0.2.151
   Compiling proc-macro2 v1.0.74
   Compiling unicode-ident v1.0.12
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling serde v1.0.194
   Compiling memchr v2.7.1
   Compiling crossbeam-utils v0.8.18
   Compiling regex-syntax v0.8.2
   Compiling once_cell v1.19.0
   Compiling libm v0.2.8
   Compiling zerocopy v0.7.32
   Compiling rayon-core v1.12.0
   Compiling either v1.9.0
   Compiling ahash v0.8.7
   Compiling num-traits v0.2.17
   Compiling aho-corasick v1.1.2
   Compiling static_assertions v1.1.0
   Compiling siphasher v0.3.11
   Compiling allocator-api2 v0.2.16
   Compiling phf_shared v0.11.2
   Compiling itoa v1.0.10
   Compiling quote v1.0.35
   Compiling crossbeam-epoch v0.9.17
   Compiling crc32fast v1.3.2
   Compiling syn v2.0.46
   Compiling getrandom v0.2.11
   Compiling jobserver v0.1.27
   Compiling crossbeam-deque v0.8.4
   Compiling equivalent v1.0.1
   Compiling futures-core v0.3.30
   Compiling cc v1.0.83
   Compiling regex-automata v0.4.3
   Compiling pin-project-lite v0.2.13
   Compiling rand_core v0.6.4
   Compiling serde_json v1.0.110
   Compiling ryu v1.0.16
   Compiling rand v0.8.5
   Compiling slab v0.4.9
   Compiling pkg-config v0.3.28
   Compiling rayon v1.8.0
   Compiling target-features v0.1.5
   Compiling futures-sink v0.3.30
   Compiling phf_generator v0.11.2
   Compiling rle-decode-fast v1.0.3
   Compiling snap v1.1.1
   Compiling phf_codegen v0.11.2
   Compiling libflate_lz77 v1.2.0
   Compiling futures-channel v0.3.30
   Compiling phf v0.11.2
   Compiling crc-catalog v1.1.1
   Compiling zstd-sys v2.0.9+zstd.1.5.5
   Compiling array-init-cursor v0.2.0
   Compiling fallible-streaming-iterator v0.1.9
   Compiling futures-io v0.3.30
   Compiling futures-task v0.3.30
   Compiling thiserror v1.0.56
   Compiling syn v1.0.109
   Compiling adler32 v1.2.0
   Compiling pin-utils v0.1.0
   Compiling libflate v1.4.0
   Compiling regex v1.10.2
   Compiling planus v0.3.1
   Compiling parse-zoneinfo v0.3.0
   Compiling crc v2.1.0
   Compiling lz4-sys v1.9.4
   Compiling smartstring v1.0.1
   Compiling hashbrown v0.14.3
   Compiling chrono-tz-build v0.2.1
   Compiling simdutf8 v0.1.4
   Compiling zstd-safe v7.0.0
   Compiling iana-time-zone v0.1.59
   Compiling polars-utils v0.37.0
   Compiling sysinfo v0.30.3
   Compiling lexical-util v0.8.5
   Compiling chrono-tz v0.8.5
   Compiling polars-arrow v0.37.0
   Compiling atoi v2.0.0
   Compiling lock_api v0.4.11
   Compiling itoap v1.0.1
   Compiling ethnum v1.5.0
   Compiling atoi_simd v0.15.6
   Compiling dyn-clone v1.0.16
   Compiling fast-float v0.2.0
   Compiling strength_reduce v0.2.4
   Compiling streaming-iterator v0.1.9
   Compiling foreign_vec v0.1.0
   Compiling serde_derive v1.0.194
   Compiling futures-macro v0.3.30
   Compiling thiserror-impl v1.0.56
   Compiling bytemuck_derive v1.5.0
   Compiling parking_lot_core v0.9.9
   Compiling rustversion v1.0.14
   Compiling futures-util v0.3.30
   Compiling bytemuck v1.14.0
   Compiling scopeguard v1.2.0
   Compiling smallvec v1.11.2
   Compiling lexical-write-integer v0.8.5
   Compiling lexical-parse-integer v0.8.6
   Compiling hashbrown v0.13.2
   Compiling ref-cast v1.0.22
   Compiling ppv-lite86 v0.2.17
   Compiling lexical-parse-float v0.8.5
   Compiling parking_lot v0.12.1
   Compiling rand_chacha v0.3.1
   Compiling lexical-write-float v0.8.5
   Compiling ref-cast-impl v1.0.22
   Compiling float-cmp v0.9.0
   Compiling polars-compute v0.37.0
   Compiling glob v0.3.1
   Compiling heck v0.4.1
   Compiling multiversion-macros v0.7.3
   Compiling lexical-core v0.8.5
   Compiling polars-core v0.37.0
   Compiling strum v0.25.0
   Compiling strum_macros v0.25.3
   Compiling clang-sys v1.7.0
   Compiling futures-executor v0.3.30
   Compiling async-trait v0.1.77
   Compiling futures v0.3.30
   Compiling unicode-width v0.1.11
   Compiling alloc-no-stdlib v2.0.4
   Compiling log v0.4.20
   Compiling alloc-stdlib v0.2.2
   Compiling rand_distr v0.4.3
   Compiling polars-ops v0.37.0
   Compiling unicode-segmentation v1.10.1
   Compiling xxhash-rust v0.8.8
   Compiling adler v1.0.2
   Compiling minimal-lexical v0.2.1
   Compiling base64 v0.21.5
   Compiling libloading v0.8.1
   Compiling miniz_oxide v0.7.1
   Compiling nom v7.1.3
   Compiling unicode-reverse v1.0.8
   Compiling brotli-decompressor v2.5.1
   Compiling async-stream-impl v0.3.5
   Compiling argminmax v0.6.1
   Compiling socket2 v0.5.5
   Compiling mio v0.8.10
   Compiling multiversion v0.7.3
   Compiling num_cpus v1.16.0
   Compiling seq-macro v0.3.5
   Compiling hex v0.4.3
   Compiling bindgen v0.69.1
   Compiling bytes v1.5.0
   Compiling cexpr v0.6.0
   Compiling async-stream v0.3.5
   Compiling indexmap v2.1.0
   Compiling chrono v0.4.31
   Compiling polars-arrow-format v0.1.0
   Compiling halfbrown v0.2.4
   Compiling bitflags v2.4.1
   Compiling value-trait v0.8.0
   Compiling crossterm v0.27.0
   Compiling tokio v1.35.1
   Compiling parquet-format-safe v0.2.4
   Compiling brotli v3.4.0
   Compiling flate2 v1.0.28
   Compiling comfy-table v7.1.0
   Compiling avro-schema v0.3.0
   Compiling polars-error v0.37.0
   Compiling simd-json v0.13.4
   Compiling now v0.1.3
   Compiling jsonpath_lib v0.3.0 (https://github.com/ritchie46/jsonpath?rev=24eaf0b4416edff38a4d1b6b17bc4b9f3f047b4b#24eaf0b4)
   Compiling streaming-decompression v0.1.2
   Compiling rustc-hash v1.1.0
   Compiling lazy_static v1.4.0
   Compiling peeking_take_while v0.1.2
   Compiling shlex v1.2.0
   Compiling lazycell v1.3.0
   Compiling tokio-util v0.7.10
   Compiling memmap2 v0.7.1
   Compiling polars-plan v0.37.0
   Compiling shell-words v1.1.0
   Compiling percent-encoding v2.3.1
   Compiling home v0.5.9
   Compiling polars-pipe v0.37.0
   Compiling crossbeam-queue v0.3.10
   Compiling crossbeam-channel v0.5.10
   Compiling polars-lazy v0.37.0
   Compiling jemalloc-sys v0.5.4+5.3.0-patched
   Compiling enum_dispatch v0.3.12
   Compiling rb-sys-env v0.1.2
   Compiling sqlparser v0.39.0
   Compiling magnus v0.6.2
   Compiling polars v0.37.0
   Compiling magnus-macros v0.6.0
   Compiling rb-sys-build v0.9.86
   Compiling rb-sys v0.9.86
   Compiling lz4 v1.24.0
error: failed to run custom build command for `rb-sys v0.9.86`

Caused by:
process didn't exit successfully:
`/home/denjamio/.rvm/gems/ruby-3.2.3/bundler/gems/polars-ruby-30b14de12d61/ext/polars/target/release/build/rb-sys-d2c7ed316f525bb6/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RUBY
  cargo:rerun-if-env-changed=RBCONFIG_CROSS_COMPILING
  cargo:rerun-if-env-changed=RBCONFIG_RUBY_PROGRAM_VERSION
  cargo:rerun-if-env-changed=RBCONFIG_platform
  cargo:rerun-if-env-changed=RUBY_ROOT
  cargo:rerun-if-env-changed=RUBY_VERSION
  cargo:rerun-if-env-changed=RUBY
  cargo:rerun-if-changed=build/features.rs
  cargo:rerun-if-changed=build/main.rs
  cargo:rerun-if-changed=build/stable_api_config.rs
  cargo:rerun-if-changed=build/version.rs
  cargo:rerun-if-env-changed=RUBY_STATIC
  cargo:rerun-if-env-changed=RBCONFIG_ENABLE_SHARED
  cargo:rerun-if-env-changed=RBCONFIG_rubyhdrdir
  cargo:rerun-if-env-changed=RBCONFIG_rubyarchhdrdir
  cargo:rerun-if-env-changed=RBCONFIG_CPPFLAGS
  cargo:rerun-if-env-changed=RBCONFIG_rubyhdrdir
  cargo:rerun-if-env-changed=RBCONFIG_MAJOR
  cargo:rerun-if-env-changed=RBCONFIG_MINOR
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
INFO: using bindgen with clang args: ["-I/home/denjamio/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0", "-I/home/denjamio/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/x86_64-linux",      
"-fms-extensions", "-O3", "-fno-fast-math", "-ggdb3", "-Wall", "-Wextra", "-Wdeprecated-declarations", "-Wdiv-by-zero", "-Wduplicated-cond", "-Wimplicit-function-declaration",     
"-Wimplicit-int", "-Wmisleading-indentation", "-Wpointer-arith", "-Wwrite-strings", "-Wold-style-definition", "-Wimplicit-fallthrough=0", "-Wmissing-noreturn",
"-Wno-cast-function-type", "-Wno-constant-logical-operand", "-Wno-long-long", "-Wno-missing-field-initializers", "-Wno-overlength-strings", "-Wno-packed-bitfield-compat",
"-Wno-parentheses-equality", "-Wno-self-assign", "-Wno-tautological-compare", "-Wno-unused-parameter", "-Wno-unused-value", "-Wsuggest-attribute=format",
"-Wsuggest-attribute=noreturn", "-Wunused-variable", "-Wundef"]
  #include "ruby.h"

  #ifdef HAVE_RUBY_DEBUG_H
  #include "ruby/debug.h"
  #endif
  #ifdef HAVE_RUBY_DEFINES_H
  #include "ruby/defines.h"
  #endif
  #ifdef HAVE_RUBY_ENCODING_H
  #include "ruby/encoding.h"
  #endif
  #ifdef HAVE_RUBY_FIBER_SCHEDULER_H
  #include "ruby/fiber/scheduler.h"
  #endif
  #ifdef HAVE_RUBY_INTERN_H
  #include "ruby/intern.h"
  #endif
  #ifdef HAVE_RUBY_IO_H
  #include "ruby/io.h"
  #endif
  #ifdef HAVE_RUBY_MEMORY_VIEW_H
  #include "ruby/memory_view.h"
  #endif
  #ifdef HAVE_RUBY_MISSING_H
  #include "ruby/missing.h"
  #endif
  #ifdef HAVE_RUBY_ONIGMO_H
  #include "ruby/onigmo.h"
  #endif
  #ifdef HAVE_RUBY_ONIGURUMA_H
  #include "ruby/oniguruma.h"
  #endif
  #ifdef HAVE_RUBY_RACTOR_H
  #include "ruby/ractor.h"
  #endif
  #ifdef HAVE_RUBY_RANDOM_H
  #include "ruby/random.h"
  #endif
  #ifdef HAVE_RUBY_RE_H
  #include "ruby/re.h"
  #endif
  #ifdef HAVE_RUBY_REGEX_H
  #include "ruby/regex.h"
  #endif
  #ifdef HAVE_RUBY_RUBY_H
  #include "ruby/ruby.h"
  #endif
  #ifdef HAVE_RUBY_ST_H
  #include "ruby/st.h"
  #endif
  #ifdef HAVE_RUBY_THREAD_H
  #include "ruby/thread.h"
  #endif
  #ifdef HAVE_RUBY_THREAD_NATIVE_H
  #include "ruby/thread_native.h"
  #endif
  #ifdef HAVE_RUBY_UTIL_H
  #include "ruby/util.h"
  #endif
  #ifdef HAVE_RUBY_VERSION_H
  #include "ruby/version.h"
  #endif
  #ifdef HAVE_RUBY_VM_H
  #include "ruby/vm.h"
  #endif
  #ifdef HAVE_RUBY_WIN32_H
  #include "ruby/win32.h"
  #endif
  #ifdef HAVE_RUBY_IO_BUFFER_H
  #include "ruby/io/buffer.h"
  #endif
  #ifdef HAVE_RUBY_ATOMIC_H
  #include "ruby/atomic.h"
  #endif
  struct rb_sys__Opaque__RString { struct RString dummy; };
  struct rb_sys__Opaque__RArray { struct RArray dummy; };
  warning: unknown warning option '-Wduplicated-cond'; did you mean '-Wduplicate-enum'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wmisleading-indentation'; did you mean '-Wbinding-in-condition'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wimplicit-fallthrough=0'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wno-packed-bitfield-compat'; did you mean '-Wno-keyword-compat'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]
  /home/denjamio/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:23:10: fatal error: 'stdarg.h' file not found
  clang diag: warning: unknown warning option '-Wduplicated-cond'; did you mean '-Wduplicate-enum'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wmisleading-indentation'; did you mean '-Wbinding-in-condition'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wimplicit-fallthrough=0'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wno-packed-bitfield-compat'; did you mean '-Wno-keyword-compat'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]
  thread 'main' panicked at /home/denjamio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rb-sys-0.9.86/build/main.rs:55:6:
  generate bindings: ClangDiagnostic("/home/denjamio/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:23:10: fatal error: 'stdarg.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Makefile:564: recipe for target 'target/release/libpolars.so' failed
make: *** [target/release/libpolars.so] Error 101

make failed, exit code 2

Gem files will remain installed in /home/denjamio/.rvm/gems/ruby-3.2.3/bundler/gems/polars-ruby-30b14de12d61 for inspection.
Results logged to /home/denjamio/.rvm/gems/ruby-3.2.3/bundler/gems/extensions/x86_64-linux/3.2.0/polars-ruby-30b14de12d61/gem_make.out

  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:53:in `block in make'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:45:in `each'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:45:in `make'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in `build_extension'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block in build_extensions'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `build_extensions'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/installer.rb:846:in `build_extensions'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/source/path/installer.rb:28:in `post_install'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/source/path.rb:244:in `generate_bin'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/source/git.rb:201:in `install'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  /home/denjamio/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing polars-df (0.8.0), and Bundler cannot continue.

In Gemfile:
  polars-df

**Comment by ankane** [comment]
Hi @denjamio, from the error message (`fatal error: 'stdarg.h' file not found`), it looks like there may be an issue with your build environment. You could try reinstalling Xcode Command Line Tools to see if that fixes it.

I've also updated `rb-sys` to the latest version in 51317ef8c46846f010da5d6986575386b3aea988.

**Comment by denjamio** [comment]
@ankane I have tried with docker but I get another error: 
#13 70.02 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#13 70.02 
#13 70.02 current directory:
#13 70.02 /usr/local/bundle/bundler/gems/polars-ruby-51317ef8c468/ext/polars
#13 70.02 /usr/local/bin/ruby extconf.rb
#13 70.02 checking for gcc... yes
#13 70.02 checking for g++... yes
#13 70.02 checking for gcc-ar... yes
#13 70.02 
#13 70.02 current directory:
#13 70.02 /usr/local/bundle/bundler/gems/polars-ruby-51317ef8c468/ext/polars
#13 70.02 make DESTDIR\= sitearchdir\=./.gem.20240221-7-shpbq3
#13 70.02 sitelibdir\=./.gem.20240221-7-shpbq3 clean
#13 70.02 
#13 70.02 current directory:
#13 70.02 /usr/local/bundle/bundler/gems/polars-ruby-51317ef8c468/ext/polars
#13 70.02 make DESTDIR\= sitearchdir\=./.gem.20240221-7-shpbq3
#13 70.02 sitelibdir\=./.gem.20240221-7-shpbq3
#13 70.02 generating target/release/libpolars.so (release)
#13 70.02 cargo rustc  --manifest-path ./Cargo.toml --target-dir target --lib --profile
#13 70.02 release -- -C linker=gcc -L native=/usr/local/lib -C link-arg=-lm -l pthread
#13 70.02 make: cargo: No such file or directory
#13 70.02 make: *** [Makefile:565: target/release/libpolars.so] Error 127
#13 70.02 
#13 70.02 make failed, exit code 2
#13 70.02 
#13 70.02 Gem files will remain installed in
#13 70.02 /usr/local/bundle/bundler/gems/polars-ruby-51317ef8c468 for inspection.
#13 70.02 Results logged to
#13 70.02 /usr/local/bundle/bundler/gems/extensions/aarch64-linux/3.2.0/polars-ruby-51317ef8c468/gem_make.out
#13 70.02 
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:53:in `block in make'
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:45:in `each'
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:45:in `make'
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in `build_extension'
#13 70.02 /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block in
#13 70.02 build_extensions'
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `build_extensions'
#13 70.02   /usr/local/lib/ruby/3.2.0/rubygems/installer.rb:846:in `build_extensions'
#13 70.02 /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in
#13 70.02 `build_extensions'
#13 70.02 /usr/local/lib/ruby/3.2.0/bundler/source/path/installer.rb:28:in
#13 70.02 `post_install'
#13 70.02   /usr/local/lib/ruby/3.2.0/bundler/source/path.rb:244:in `generate_bin'
#13 70.02   /usr/local/lib/ruby/3.2.0/bundler/source/git.rb:201:in `install'
#13 70.02   /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
#13 70.02 /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in
#13 70.02 `install_from_spec'
#13 70.02 /usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in
#13 70.02 `do_install'
#13 70.02 /usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in
#13 70.02 `block in worker_pool'
#13 70.02   /usr/local/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
#13 70.02   /usr/local/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
#13 70.02   /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
#13 70.02   /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
#13 70.02 /usr/local/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in
#13 70.02 create_threads'
#13 70.02 
#13 70.02 An error occurred while installing polars-df (0.8.0), and Bundler cannot
#13 70.02 continue.
#13 70.02 
#13 70.02 In Gemfile:
#13 70.02   polars-df
------
executor failed running [/bin/sh -c bundle install]: exit code: 5


**- In dockerfile:** 
# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential ruby-dev git libpq-dev libvips pkg-config

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install


I don't know if I'm missing a specific package that might need the gem. I'm a bit confused about this

**Comment by kojix2** [comment]
Maybe you don't have Rust installed.

**Comment by ankane** [comment]
It looks like that's the case.

```text
make: cargo: No such file or directory
```

The minimum Rust version needed was [1.73.0](https://github.com/ankane/polars-ruby/blob/51317ef8c46846f010da5d6986575386b3aea988/ext/polars/Cargo.toml#L7) last time I checked.

**Comment by denjamio** [comment]
right, after add rust to the dockerfile its work. thanks!
