### ISSUE TITLE
With the release tags, specify what version of the underlying Rust polars library/API you're using

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/polars-ruby#50]
In the GitHub Releases, it would be really helpful if you specified in the release notes which version each release is associated with. The Rust API changes a bit (and knowing the semantics of which docs version to look at is helpful). Thanks!

**Comment by ankane** [comment]
Hi @DeflateAwning, the Rust version is in the changelog.

**Comment by DeflateAwning** [comment]
Thoughts on releasing the changelog in the GitHub Releases section? It's pretty standard on projects like this, and is a little easier to reference as well!
