### ISSUE TITLE
Request: add support for `df.write_json(nil)`, which returns the JSON as a string

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/polars-ruby#51]
`df.write_json(None)` is supported in Python, and can be used to return the dataframe as a JSON string right away (instead of writing to a file and then reading the file). It would be awesome if support for that was added here!

**Comment by DeflateAwning** [comment]
Wow, thanks a lot! Very impressive implementation speed! Looking forward to trying it out in the next release!

**Comment by DeflateAwning** [comment]
Would you mind tagging a new release with this change in it?

**Comment by Antti** [comment]
Any chance we can have that for all the `.write` calls?
`parquet` for example? Currently I have to write it to temp file and read it afterwards, feels hacking.

**Comment by DeflateAwning** [comment]
A new issue is probably best for tracking.

Just note that binary formats (e.g., parquet) [don't support this behaviour in the core Rust/Python library](https://docs.pola.rs/py-polars/html/reference/api/polars.DataFrame.write_parquet.html#polars.DataFrame.write_parquet), so there's probably a low chance it'll be supported here.

**Comment by ankane** [comment]
@Antti Added support for writing to `StringIO` in the commit above.

```ruby
io = StringIO.new
df.write_parquet(io)
p io.string
```

@DeflateAwning I don't plan to make a new release for this.
