### ISSUE TITLE
Idea: have you ever thought about making geopolars-ruby?

### ISSUE THREAD

**Issue by DeflateAwning** [ankane/polars-ruby#52]
Your port here is extremely impressive. Both the quality of the port, as well as the speed of bug fixes, makes this port very very impressive.

I was wondering if you've ever thought about porting [GeoPolars](https://geopolars.org/latest/), an experimental geopandas-like polars library (native in Python and Rust). Am curious if you could advise on how insane such an effort would be?

Seems like the support for fast geo support in Python is rather limited (geopandas, arcgis, etc. are our slowest and least reliable dependencies); the situation in Ruby is even moreso.

**Comment by ankane** [comment]
Thanks @DeflateAwning. I hadn't seen it until now and don't think it's something I'll do, but the API doesn't look very large.
