### ISSUE TITLE
Ship polars 0.91 release

### ISSUE THREAD

**Issue by woodhull** [ankane/polars-ruby#63]
The pending polars 0.91 gem release will be a huge improvement for us. 

Our current work-around while we're waiting for the pre-compiled binary that supports musl libc makes our docker build process extremely slow (a few minutes to over an hour) since it needs to compile all of the rust dependencies anytime our Gemfile.lock changes or our cache is cleared.

**Comment by DeflateAwning** [comment]
Just wanted to bump this. We have a build pipeline that has to rebuild the entire thing from source right now; it takes almost 40 minutes. Would be use to ship a `0.9.1` release!

**Comment by ankane** [comment]
Just pushed 0.10.0.
