### ISSUE TITLE
Cannot chain WhenThen together due to missing module

### ISSUE THREAD

**Issue by tios-jleclear** [ankane/polars-ruby#64]
When you try to chain Polars.when(expr).then(expr).when(expr).then(expr).... in the manner that it shows [here](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.when.html#polars.when) you get a `gems/polars-df-0.8.0-arm64-darwin/lib/polars/when_then.rb:11:in `when': uninitialized constant Polars::WhenThen::WhenThenThen (NameError)
` due to the missing module WhenThenThen. I believe this should just be a WhenThen.new rather than a WhenThenThen

**Comment by ankane** [comment]
Hi @tios-jleclear, thanks for reporting! Fixed in the commit above.
