### ISSUE TITLE
Would be awesome to have support for multifile csv read 🤩

### ISSUE THREAD

**Issue by warrenbhw** [ankane/polars-ruby#7]
Error when using a `*` wildcard in path for `read_csv`: lib/polars/data_frame.rb:127:in `_read_csv': not implemented yet (Polars::Todo)

**Comment by ankane** [comment]
Hey @warrenbhw, added in the commit above.

**Comment by warrenbhw** [comment]
That was so quick. Elite 🙏🙇‍♂️ thanks for all your work on the project!
